#---------------------------------------------------
# Composite action (Send Email Notification)
#---------------------------------------------------

name: Workflow Email Notification
description: Composite action to send email notification for workflow status

inputs:
  username:
    required: true
    description: "SMTP username (email address)"

  password:
    required: true
    description: "SMTP password (app-specific or token)"

  to:
    required: true
    description: "Comma-separated recipient email addresses"

  workflow_success:
    required: true
    description: "Work flow status ('true' or 'false')"

  whats_new:
    required: false
    description: "JSON array of what's new entries"

  bug_fixes:
    required: false
    description: "JSON array of bug fixes entries"

  artifacts:
    required: false
    description: "JSON array of artifacts with 'label' and 'url'"

runs:
  using: "composite"

  steps:
    - name: Install Python dependencies
      shell: bash
      run: |
        pip install --quiet jinja2

    - name: Generate email subject
      id: email_subject
      shell: bash
      run: |
        if [[ "${{ inputs.workflow_success }}" == "true" ]]; then
          SUBJECT="[🟢 Workflow] ${{ github.workflow }} #${{ github.run_number }} of ${{ github.repository }} completed successfully"
        else
          SUBJECT="[🔴 Workflow] ${{ github.workflow }} #${{ github.run_number }} of ${{ github.repository }} failed to complete"
        fi

        echo "subject=$SUBJECT" >> "$GITHUB_OUTPUT"

    - name: Generate email body
      id: email_body
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        WORKFLOW_NAME: ${{ github.workflow }}
        BRANCH_TAG: ${{ github.ref_name }}
        COMMIT_SHA: ${{ github.sha }}
        TRIGGERED_BY: ${{ github.actor }}
        RUN_NUMBER: ${{ github.run_number }}
        RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}     
        WORKFLOW_SUCCESS: ${{ inputs.workflow_success }}
        WHATS_NEW: ${{ inputs.whats_new }}
        BUG_FIXES: ${{ inputs.bug_fixes }}
        ARTIFACTS: ${{ inputs.artifacts }}
      run: |

        EMAIL_BODY_FILE="email-body-${RUN_ID}.html"

        python3 ".github/actions/workflow-email-notification/generate-email-template.py" \
          --template ".github/actions/workflow-email-notification/workflow-email-template.j2" \
          --output "$EMAIL_BODY_FILE"

        echo "html_body=$EMAIL_BODY_FILE" >> "$GITHUB_OUTPUT"

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        from: ${{ inputs.username }}
        to: ${{ inputs.to }}
        subject: ${{ steps.email_subject.outputs.subject }}
        html_body: file://${{ steps.email_body.outputs.html_body }}

