#---------------------------------------------------
# Composite action (Remove Docker Self-hosted Runner)
#---------------------------------------------------
name: Remove Dynamic Self-hosted Linux Docker Runner
description: Composite action to stop Docker container and de-register GitHub Actions runner

inputs:
  label:
    required: true
    description: "Name of the Docker container (same as runner label)"

runs:
  using: "composite"
  steps:

    - name: Stop and remove Docker container
      shell: bash
      run: |
        echo ""
        echo "[INFO] Stopping container: ${{ inputs.label }}"
        docker container stop ${{ inputs.label }} || true

        echo ""
        echo "[INFO] Running containers:"
        docker ps --format "table {{ .ID }}\t{{ .Image }}\t{{ .Names }}\t{{ .Status }}"
