#---------------------------------------------------
# Composite action (upload artifact to JFrog Artifactory)
#---------------------------------------------------
name: JFrog Upload Artifact
description: Composite action to upload artifact to JFrog Artifactory

inputs:
  jf_url:
    required: true
    description: "Artifactory base URL"

  jf_username:
    required: true
    description: "Artifactory Authentication Username"

  jf_secret:
    required: true
    description: "Artifactory Authentication Password/Token"

  local_artifact_path:
    required: true
    description: "Absolute path to local artifact"

  artifact_upload_repo_path:
    required: true
    description: "Artifactory repository name to upload artifact"

runs:
  using: "composite"
  steps:
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 'latest'

    - name: Configure JFrog CLI
      shell: python
      env:
        JF_URL: ${{ inputs.jf_url }}
        JF_USERNAME: ${{ inputs.jf_username }}
        JF_SECRET: ${{ inputs.jf_secret }}
        LOCAL_PATH: ${{ inputs.local_artifact_path }}
        REMOTE_PATH: ${{ inputs.artifact_upload_repo_path }}
      run: |
        import os
        import platform
        from subprocess import run

        jf_url = os.environ["JF_URL"]
        jf_user = os.environ["JF_USERNAME"]
        jf_pass = os.environ["JF_SECRET"]
        local = os.environ["LOCAL_PATH"]
        remote = os.environ["REMOTE_PATH"]

        cmd_config = f'jf c add artifactory --url="{jf_url}" --user="{jf_user}" --password="{jf_pass}" --overwrite=true --interactive=false'
        
        cmd_upload = f'jf rt upload "{local}" "{remote}" --flat=true'

        run(cmd_config, shell=True)
        run(cmd_upload, shell=True)
    
