#---------------------------------------------------
# Composite action (Upload artifact to JFrog Artifactory)
#---------------------------------------------------
name: JFrog Upload Artifact
description: Composite action to upload artifact to JFrog Artifactory

inputs:
  artifactory_url:
    required: true
    description: "Artifactory base URL"

  artifactory_username:
    required: true
    description: "Artifactory Authentication Username"

  artifactory_password:
    required: true
    description: "Artifactory Authentication Password/Token"

  local_artifact_path:
    required: true
    description: "Absolute path to local artifact"

  remote_repo_path:
    required: true
    description: "Artifactory repository path to upload artifact"

runs:
  using: "composite"
  steps:

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 'latest'

    - name: Upload artifact to Artifactory
      shell: python
      env:
        artifactory_url: ${{ inputs.artifactory_url }}
        artifactory_username: ${{ inputs.artifactory_username }}
        artifactory_password: ${{ inputs.artifactory_password }}
        local_artifact_path: ${{ inputs.local_artifact_path }}
        remote_repo_path: ${{ inputs.remote_repo_path }}
      run: |
        import os
        import subprocess

        url = os.environ["artifactory_url"]
        username = os.environ["artifactory_username"]
        password = os.environ["artifactory_password"]
        local_path = os.environ["local_artifact_path"]
        remote_path = os.environ["remote_repo_path"]

        #---------------------------------------------------
        # Upload artifact
        #---------------------------------------------------
        subprocess.run([
            "jf", "rt", "u",
            f"--url={url}",
            f"--user={username}",
            f"--password={password}",
            "--insecure-tls=true",
            "--flat=true",
            local_path,
            remote_path
        ], check=True)