#---------------------------------------------------
# Composite action (Setup Docker Self-hosted Runner)
#---------------------------------------------------
name: Setup Dynamic Self-hosted Linux Docker Runner
description: Composite action to start Docker container and register GitHub Actions runner

inputs:
  docker_registry:
    required: true
    description: "Docker registry URL"

  docker_image:
    required: true
    description: "Docker image to start container"

  artifactory_url:
    required: true
    description: "Artifactory base URL"

  artifactory_username:
    required: true
    description: "Artifactory Authentication Username"

  artifactory_password:
    required: true
    description: "Artifactory Authentication Password"

  runner_setup_path:
    required: true
    description: "Artifactory path of Actions Runner setup for Linux"

  workflow_ci_token:
    required: true
    description: "Workflow access token to call GitHub REST APIs"

outputs:

  label:
    value: ${{ steps.generate_label.outputs.label }}
    description: "Unique label assigned to the dynamic GitHub runner"

  runs_on:
    value: ${{ steps.generate_label.outputs.runs_on }}
    description: "JSON array of runner labels to be used in the 'runs-on' field"

runs:
  using: "composite"
  steps:

    - name: Generate Dynamic Runner Label
      id: generate_label
      shell: bash
      run: |
        LABEL="docker-${GITHUB_REPOSITORY##*/}-${GITHUB_RUN_NUMBER}"
        RUNS_ON="[\"self-hosted\", \"${LABEL}\"]"
        echo "label=${LABEL}" >> $GITHUB_OUTPUT
        echo "runs_on=${RUNS_ON}" >> $GITHUB_OUTPUT

    - name: Login to Docker Registry
      shell: bash
      run: |
        echo "${{ inputs.artifactory_password }}" | docker login -u "${{ inputs.artifactory_username }}" --password-stdin ${{ inputs.docker_registry }}
        
    - name: Start Docker runner
      shell: bash
      run: |
        echo ""
        echo "[INFO] Starting container and register runner"

        docker run -d --rm \
          --name ${{ steps.generate_label.outputs.label }} \
          -e ENABLE_GITHUB_RUNNER="true" \
          -e ARTIFACTORY_URL="${{ inputs.artifactory_url }}" \
          -e ARTIFACTORY_USERNAME="${{ inputs.artifactory_username }}" \
          -e ARTIFACTORY_PASSWORD="${{ inputs.artifactory_password }}" \
          -e RUNNER_SETUP_ARTIFACTORY_PATH="${{ inputs.runner_setup_path }}" \
          -e GITHUB_REPO_NAME="${GITHUB_REPOSITORY}" \
          -e GITHUB_ACCESS_TOKEN="${{ inputs.workflow_ci_token }}" \
          -e RUNNER_NAME="${{ steps.generate_label.outputs.label }}" \
          -e RUNNER_LABELS="${{ steps.generate_label.outputs.label }}" \
          ${{ inputs.docker_registry }}/${{ inputs.docker_image }}

        # Check the running container
        echo ""
        echo "[INFO] Running containers:"
        docker ps --format "table {{ .ID }}\t{{ .Image }}\t{{ .Names }}\t{{ .Status }}"

        # Wait for a short period to allow runner registration
        echo ""
        echo "[INFO] Waiting for a short period to allow runner registration..."
        sleep 10

        # Display the container logs
        echo ""
        echo "[INFO] Container logs:"
        docker logs ${{ steps.generate_label.outputs.label }} || true
