#---------------------------------------------------
# Composite action (Send Email Notification)
#---------------------------------------------------

name: Send Email Notification
description: Composite action to send an email notification

inputs:
  username:
    required: true
    description: "SMTP username (email address)"

  password:
    required: true
    description: "SMTP password (app-specific or token)"

  to:
    required: true
    description: "Comma-separated recipient email addresses"

  subject:
    required: true
    description: "Email subject line"

  body:
    required: false
    description: "Email body as plain text"

  html_body:
    required: false
    description: "Email body as HTML"

runs:
  using: "composite"
  steps:

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        from: ${{ inputs.username }}
        to: ${{ inputs.to }}
        subject: ${{ inputs.subject }}
        body: ${{ inputs.body }}
        html_body: ${{ inputs.html_body }}

