name: Action Tester - Upload Artifact to Artifactory

on:
  workflow_dispatch:
    inputs:
      artifactory_url:
        description: "Artifactory base URL"
        required: true
        default: "https://artifactory.matrixcomsec.org/artifactory"

      artifactory_username:
        description: "Artifactory username"
        required: true
        default: "admin"

      artifactory_password:
        description: "Artifactory password/token"
        required: true
        default: "Matrix@123"

      local_artifact_path:
        description: "Absolute path to the local artifact"
        required: false
        default: "README.md"

      remote_repo_path:
        description: "Artifactory remote repository path"
        required: false
        default: "test-repo/"

jobs:
  jfrog_deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Upload Artifact to JFrog Artifactory
      uses: ravikansangara/base-project/.github/actions/jfrog-upload-artifact@main
      with: 
        artifactory_url: ${{ github.event.inputs.artifactory_url }}
        artifactory_username: ${{ github.event.inputs.artifactory_username }}
        artifactory_password: ${{ github.event.inputs.artifactory_password }}
        local_artifact_path: ${{ github.event.inputs.local_artifact_path }}
        remote_repo_path: ${{ github.event.inputs.remote_repo_path }}
