name: Action Tester - Workflow Email Notification

on:
  push:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: "SMTP username (email address)"
        default: 'kansangara.ravi@gmail.com'

      password:
        required: true
        description: "SMTP password"
        default: 'eysq aqbu fheg zqhh'

      from:
        required: true
        description: "Sender's full name (Name <email-address>)"
        default: 'Ravi Kansangara <kansangara.ravi@gmail.com>'

      to_addresses:
        description: 'Comma-separated email recipients'
        required: true
        default: 'kansangara.ravi@gmail.com'

      status:
        description: 'Notification Type'
        required: true
        default: 'success'
        type: choice
        options: [success, failure]

      whats_new:
        description: "What's new (JSON array)"
        required: false
        default: '["Improved performance", "New API support"]'

      bug_fixes:
        description: "Bug fixes (JSON array)"
        required: false
        default: '["Fixed login issue", "Resolved crash on iOS"]'

      artifacts:
        description: "Artifacts (JSON array of label-url pairs)"
        required: false
        default: '[{"label": "Product Artifact", "url": "https://artifactory.matrixcomsec.org/repo-path/artifact.zip"}]'

jobs:
  workflow_email_notification:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Send Email Notification
      uses: ravikansangara/base-project/.github/actions/workflow-email-notification@main
      with: 
        username: ${{ github.event.inputs.username }}
        password: ${{ github.event.inputs.password }}
        from: ${{ github.event.inputs.from }}
        to: ${{ github.event.inputs.to_addresses }}
        workflow_success: ${{ github.event.inputs.status == 'success' && 'true' || 'false' }}
        whats_new: ${{ github.event.inputs.whats_new }}
        bug_fixes: ${{ github.event.inputs.bug_fixes }}
        artifacts: ${{ github.event.inputs.artifacts }}
