name: Build

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

  # JFrog server URL
  JF_URL: ${{ vars.JF_URL }}

  # JFrog authentication credentials
  JF_USER: ${{ secrets.JF_USER }}
  JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

  # JFrog artifact upload repository path
  LOCAL_ARTIFACT_PATH: "build/base_app"
  SW_PACKAGE_NAME: "my-product-v${{ github.run_number }}.zip"
  JF_ARTIFACT_UPLOAD_REPO_PATH: "product-prod-release/product-v${{ github.run_number }}/"

jobs:
  build_and_deploy:
    runs-on: [self-hosted, build]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Create Software Package
      run: |
        cd build
        zip -r "../${{ env.SW_PACKAGE_NAME }}" base_app
      shell: bash

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ env.SW_PACKAGE_NAME }}
        path: ${{ github.workspace }}/${{ env.SW_PACKAGE_NAME }}
        if-no-files-found: error
        retention-days: 1

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 'latest'

    - name: Configure JFrog CLI
      run: |
        jf c add artifactory --url="${{ env.JF_URL }}" --user="${{ env.JF_USER }}" --password="${{ env.JF_PASSWORD }}" --overwrite=true --interactive=false

    - name: Upload Artifact to JFrog Artifactory
      run: jf rt upload "${{ github.workspace }}/${{ env.SW_PACKAGE_NAME }}" "${{ env.JF_ARTIFACT_UPLOAD_REPO_PATH }}" --flat=true

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        subject: "Build successful!"
        body: "<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>GitHub Actions Notification</title>
		<link
			href="https://fonts.googleapis.com/css?family=Google+Sans:300,400,500,700&display=swap"
			rel="stylesheet" />
		<link
			href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
			rel="stylesheet" />
		<style>
			body {
				font-family: "Product Sans", "Segoe UI", sans-serif;
				margin: 0;
				padding: 0;
				background-color: #e9eef6;
				color: #303134;
				display: flex;
				justify-content: center;
				align-items: center;
				min-height: 100vh;
			}

			.card-container {
				width: 100%;
				max-width: 70vw;
				background-color: #f8fafd;
				border-radius: 12px;
				box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
			}

			.header-success {
				background-color: #d32f2f;
				color: white;
				padding: 20px;
				font-size: 24px;
				display: flex;
				align-items: center;
				border-radius: 12px 12px 0 0;
			}

			.header-icon {
				font-size: 32px;
				margin-right: 12px;
			}

			.card-body {
				padding: 30px;
			}

			.flex-row {
				display: flex;
				flex-wrap: wrap;
				gap: 30px;
				justify-content: space-between;
			}

			.section {
				flex: 1;
				display: flex;
				flex-direction: column;
			}

			.section-title {
				display: flex;
				align-items: center;
				font-size: 18px;
				margin-bottom: 20px;
				line-height: 1;
			}

			.section-title-margin {
				margin-top: 30px;
			}

			.section-title .material-icons-outlined {
				line-height: 1;
				margin-right: 8px;
				vertical-align: middle;
			}

			.details {
				display: flex;
				flex-direction: column;
			}

			.detail-item {
				display: flex;
				align-items: center;
				padding: 8px 0;
				font-size: 16px;
			}

			.detail-item.column {
				flex-direction: column;
				align-items: flex-start;
			}

			.detail-key {
				color: #707174;
				min-width: 180px;
			}

			.detail-value {
				font-weight: bold;
				color: #404144;
				word-break: break-word;
			}

			ul.detail-value {
				font-weight: normal;
				padding-left: 20px;
				margin: 5px 0;
			}

			.detail-value li {
				margin-bottom: 8px;
			}

			hr {
				border: none;
				height: 1px;
				background-color: #ddd;
				margin: 5px 0;
			}

			a {
				color: #1e5de5;
			}

			.artifact-list {
				list-style: none;
				padding: 0;
				margin-top: 10px;
			}

			.artifact-item {
				display: flex;
				align-items: center;
				padding-top: 10px;
			}

			.artifact-item i {
				margin-right: 8px;
			}

			.artifact-link {
				color: #1e5de5;
				text-decoration: underline;
			}

			.footer-message {
				font-size: 14px;
				color: #777;
				text-align: center;
				padding: 15px;
				border-top: 1px solid #ddd;
				border-radius: 0 0 12px 12px;
				background-color: #f8f8f8;
			}
		</style>
	</head>
	<body>
		<div class="card-container">
			<div class="header-success">
				<span class="material-icons-outlined header-icon">report</span>
				WORKFLOW FAILED TO COMPLETE!
			</div>
			<div class="card-body">
				<div class="flex-row">
					<!-- Run Summary -->
					<div class="section">
						<div class="section-title">
							<span class="material-icons-outlined">assignment</span>
							<span>Run Summary</span>
						</div>
						<div class="details">
							<div class="detail-item">
								<span class="detail-key">Repository:</span>
								<span class="detail-value">
									<a href="https://github.com/matrix-ipvs/nvrx"
										>matrix-ipvs/nvrx</a
									>
								</span>
							</div>
							<hr />
							<div class="detail-item">
								<span class="detail-key">Workflow Name:</span>
								<span class="detail-value">Alpha Build</span>
							</div>
							<hr />
							<div class="detail-item">
								<span class="detail-key">Branch/Tag Reference:</span>
								<span class="detail-value">develop</span>
							</div>
							<hr />
							<div class="detail-item">
								<span class="detail-key">Commit SHA:</span>
								<span class="detail-value">692ed90</span>
							</div>
							<hr />
							<div class="detail-item">
								<span class="detail-key">Triggered By:</span>
								<span class="detail-value">ravi-kansangara_mtrx</span>
							</div>
							<hr />
							<div class="detail-item">
								<span class="detail-key">GitHub Run ID:</span>
								<span class="detail-value">
									<a href="{{build_url}}">#77</a>
								</span>
							</div>
							<hr />
							<div class="detail-item">
								<span class="detail-key">Run Duration:</span>
								<span class="detail-value">12m 40s</span>
							</div>
						</div>
					</div>

					<!-- Changelog -->
					<div class="section">
						<div class="section-title">
							<span class="material-icons-outlined">update</span>
							<span>Changelog</span>
						</div>
						<div class="details">
							<div class="detail-item column">
								<span class="section-title">
									<!-- <span class="material-icons-outlined">new_releases</span> -->
									<span>What's New</span>
								</span>
								<ul class="detail-value">
									<li>Added support for adaptive streaming.</li>
									<li>OTA update mechanism integrated.</li>
									<li>New event logging framework introduced.</li>
								</ul>
							</div>
							<div class="detail-item column">
								<span class="section-title">
									<!-- <span class="material-icons-outlined">bug_report</span> -->
									<span>Bug Fixes</span>
								</span>
								<ul class="detail-value">
									<li>Fixed memory leak in media encoder module.</li>
									<li>Resolved UI crash during disconnection.</li>
									<li>Corrected version label mismatch on dashboard.</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-message">
				This is an auto-generated email by GitHub Actions. Do not reply to this email.
			</div>
		</div>
	</body>
</html>
"
        to: "kansangara.ravi@gmail.com"
        from: "kansangara.ravi@gmail.com"
