
name: Email Notification

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ "main" ]

env:

  TO: "kansangara.ravi@gmail.com"
  SUBJECT: "Workflow [Alpha Build] for Product [NVRX] Completed Successfully!"
  BODY: "file://ravikansangara/base-project/.github/actions/email-notification/workflow-success-template.yml"

jobs:
  email_notification:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Send Email Notification
      uses: ravikansangara/base-project/.github/actions/email-notification@main
      with: 
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        to: ${{ env.TO }}
        subject: ${{ env.SUBJECT }}
        body: ${{ env.BODY }}
