name: Email Notification

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ "main" ]

env:
  TO: "kansangara.ravi@gmail.com, mayank.korat@matrixcomsec.com"
  SUBJECT: "[SUCCESS] ${{ github.workflow }} #${{ github.run_number }}: Completed in [${{ github.repository }}]"

jobs:

  email_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Read HTML Body from file
      id: prepare_body
      run: |
        {
          echo "body<<EOF"
          cat .github/actions/email-notification/workflow-success-template.html
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Print Email Content
      run: |
        echo -e "To: ${{ env.TO }}"
        echo -e "Subject: ${{ env.SUBJECT }}"

    - name: Send Email Notification
      uses: ravikansangara/base-project/.github/actions/email-notification@main
      with: 
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        to: ${{ env.TO }}
        subject: ${{ env.SUBJECT }}
        body: ${{ steps.prepare_body.outputs.body }}
