name: Email Notification

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      to_addresses:
        description: 'Comma-separated email recipients'
        required: true
        default: 'kansangara.ravi@gmail.com'

      status:
        description: 'Notification Type'
        required: true
        default: 'success'
        type: choice
        options:
          - success
          - failure
jobs:

  email_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare Email Subject & Body
      id: prepare_email
      run: |

        # -----------------------------------------------------------
        # Prepare Subject
        # -----------------------------------------------------------
        if [ "${{ github.event.inputs.status }}" = "success" ]; then
          SUBJECT="[SUCCESS] ${{ github.workflow }} #${{ github.run_number }} Completed in [${{ github.repository }}]"
        else
          SUBJECT="[FAILURE] ${{ github.workflow }} #${{ github.run_number }} Failed to Complete in [${{ github.repository }}]"
        fi

        echo "subject=${SUBJECT}" >> "$GITHUB_OUTPUT"

        # -----------------------------------------------------------
        # Prepare Body
        # -----------------------------------------------------------
        if [ "${{ github.event.inputs.status }}" = "success" ]; then
          BODY_TEMPLATE_FILE=".github/actions/email-notification/workflow-success-template.html"
        else
           BODY_TEMPLATE_FILE=".github/actions/email-notification/workflow-fail-template.html"
         fi
        {
          echo "body<<EOF"
          cat "$BODY_TEMPLATE_FILE"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Send Email Notification
      uses: ravikansangara/base-project/.github/actions/email-notification@main
      with: 
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        to: ${{ github.event.inputs.to_addresses }}
        subject: ${{ steps.prepare_email.outputs.subject }}
        body: ${{ steps.prepare_email.outputs.body }}
