name: Upload Artifact to Artifactory

on:
  workflow_dispatch:

env:
  LOCAL_ARTIFACT_PATH: "${{ github.workspace }}/README.md"
  REMOTE_REPO_PATH: "test-repo/run-v${{ github.run_number }}/"

jobs:
  jfrog_deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Upload Artifact to JFrog Artifactory
      uses: ravikansangara/base-project/.github/actions/jfrog-upload-artifact@main
      with: 
        artifactory_url: ${{ vars.ARTIFACTORY_URL }}
        artifactory_username: ${{ secrets.ARTIFACTORY_USERNAME }}
        artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        local_artifact_path: ${{ env.LOCAL_ARTIFACT_PATH }}
        remote_repo_path: ${{ env.JF_ARTIFACT_UPLOAD_REPO_PATH }}
