name: Playground

on:
  workflow_dispatch:

jobs:

  build-project:
    runs-on: ubuntu-latest

    steps:
    - name: Message format
      run: |
        echo "::notice::Hello World!"
        echo "::error::Hello World!"