name: Reusable Workflow

on:
  workflow_call:
    inputs:
      param:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Project
      run: |
        echo "Triggered on branch: ${{ github.ref }}"
        echo "Input param: ${{ inputs.param }}"