name: Reusable Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Print input parameters
      run: |
        echo -n "Current Git ref: "
        git describe --tags --exact-match 2>/dev/null || git branch --show-current