name: Sample Workflow

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  sample-job:
    runs-on: [self-hosted, build]

    steps:
    - name: Print a message
      run: echo "Hello World!"
