name: Github Actions Scratchpad

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:

      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'

      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        
env:
  MY_ENV_VAR: "hello world"

jobs:
  test-vars:
    runs-on: [self-hosted, codeql]

    steps:

      - name: Display predefined variable
        run: |
          echo "Predefined variable GITHUB_REPOSITORY is: $GITHUB_REPOSITORY"

      - name: Display workflow environment variable
        run: |
          echo "Environment variable MY_ENV_VAR is: ${{ env.MY_ENV_VAR }}"

      - name: Display GitHub action variable
        run: |
          echo "GitHub secret MY_ACTION_VAR is: ${{ vars.MY_ACTION_VAR }}"

      - name: Display GitHub action secret
        run: |
          echo "GitHub secret MY_SECRET_VAR is: ${{ secrets.MY_SECRET_VAR }}"
