name: Workflow Email Notification

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      to_addresses:
        description: 'Comma-separated email recipients'
        required: true
        default: 'kansangara.ravi@gmail.com'

      status:
        description: 'Notification Type'
        required: true
        default: 'success'
        type: choice
        options: [success, failure]

      whats_new:
        description: "What's new (JSON array)"
        required: false
        default: '["Improved performance", "New API support"]'

      bug_fixes:
        description: "Bug fixes (JSON array)"
        required: false
        default: '["Fixed login issue", "Resolved crash on iOS"]'

      artifacts:
        description: "Artifacts (JSON array of label-url pairs)"
        required: false
        default: '[{"label": "Build Zip", "url": "https://example.com/build.zip"}]'

jobs:

  workflow_email_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Send Email Notification
      uses: ravikansangara/base-project/.github/actions/workflow-email-notification@main
      with: 
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_PASSWORD }}
        to: ${{ github.event.inputs.to_addresses }}
        workflow_success: ${{ github.event.inputs.status == 'success' && 'true' || 'false' }}
        whats_new: ${{ github.event.inputs.whats_new }}
        bug_fixes: ${{ github.event.inputs.bug_fixes }}
        artifacts: ${{ github.event.inputs.artifacts }}
